import { test, expect } from '@playwright/test';

const escapeRegExp = (value: string) => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const mockSendPayloadKey = 'nexus-mail-mock-send-email';

test.describe('Compose and Send Email', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
    await page.evaluate((key) => localStorage.removeItem(key), mockSendPayloadKey);
    // Wait for initial load and account selection
    await expect(page.locator('button[title="demo@nexus-mail.com"]')).toBeVisible();
  });

  test('should open compose modal and send email', async ({ page }) => {
    // 1. Click Compose button
    const composeBtn = page.getByRole('button', { name: /Compose/i });
    await expect(composeBtn).toBeVisible();
    await composeBtn.click();

    // 2. Verify Modal is open
    await expect(page.getByText('New Message')).toBeVisible();

    // 3. Fill details
    await page.locator('input[placeholder="recipient@example.com"]').fill('test-receiver@nexus-mail.com');
    await page.locator('input[placeholder="cc@example.com"]').fill('cc-person@nexus-mail.com');
    await page.locator('input[placeholder="bcc@example.com"]').fill('bcc-person@nexus-mail.com');
    await page.locator('input[placeholder="Enter subject"]').fill('Test Subject from Playwright');
    await page.locator('[contenteditable="true"]').fill('This is a test message generated by automated E2E tests.');

    // 4. Click Send
    // Note: In our current implementation, we show an alert(). Playwright handles dialogs.
    page.on('dialog', async dialog => {
      expect(dialog.message()).toContain('Email sent successfully');
      await dialog.accept();
    });

    const sendBtn = page.getByRole('button', { name: /Send/i });
    await sendBtn.click();

    // 5. Modal should be closed after success
    await expect(page.getByText('New Message')).not.toBeVisible();

    const payload = await page.evaluate((key) => {
      const stored = localStorage.getItem(key);
      return stored ? JSON.parse(stored) : null;
    }, mockSendPayloadKey);

    expect(payload).toMatchObject({
      to: 'test-receiver@nexus-mail.com',
      cc: 'cc-person@nexus-mail.com',
      bcc: 'bcc-person@nexus-mail.com',
      subject: 'Test Subject from Playwright'
    });
  });

  test('should prefill reply and forward content', async ({ page }) => {
    const firstEmail = page.locator('[data-testid^="email-card-"]').first();
    await expect(firstEmail).toBeVisible();
    await firstEmail.click();

    const detailSubject = page.locator('h1').first();
    await expect(detailSubject).toBeVisible();
    const subjectText = await detailSubject.innerText();
    const fromText = await page.locator('header span.text-sm.font-bold').first().innerText();

    await page.locator('[data-testid="action-reply"]').click();
    await expect(page.getByText('New Message')).toBeVisible();
    await expect(page.locator('#to')).toHaveValue(fromText);
    await expect(page.locator('#subject')).toHaveValue(new RegExp(`^Re: .*${escapeRegExp(subjectText)}.*`));
    await page.getByRole('button', { name: /Cancel/i }).click();
    await expect(page.getByText('New Message')).not.toBeVisible();

    await page.locator('[data-testid="action-forward"]').click();
    await expect(page.getByText('New Message')).toBeVisible();
    await expect(page.locator('#subject')).toHaveValue(new RegExp(`^Fwd: .*${escapeRegExp(subjectText)}.*`));
    await page.getByRole('button', { name: /Cancel/i }).click();
  });
});
