import { test, expect } from '@playwright/test';

test.describe('Compose and Send Email', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
    // Wait for initial load and account selection
    await page.waitForSelector('select');
  });

  test('should open compose modal and send email', async ({ page }) => {
    // 1. Click Compose button
    const composeBtn = page.getByRole('button', { name: /Compose/i });
    await expect(composeBtn).toBeVisible();
    await composeBtn.click();

    // 2. Verify Modal is open
    await expect(page.getByText('New Message')).toBeVisible();

    // 3. Fill details
    await page.locator('input[placeholder="recipient@example.com"]').fill('test-receiver@nexus-mail.com');
    await page.locator('input[placeholder="Enter subject"]').fill('Test Subject from Playwright');
    await page.locator('textarea[placeholder="Write your message here..."]').fill('This is a test message generated by automated E2E tests.');

    // 4. Click Send
    // Note: In our current implementation, we show an alert(). Playwright handles dialogs.
    page.on('dialog', async dialog => {
      expect(dialog.message()).toContain('Email sent successfully');
      await dialog.accept();
    });

    const sendBtn = page.getByRole('button', { name: /Send/i });
    await sendBtn.click();

    // 5. Modal should be closed after success
    await expect(page.getByText('New Message')).not.toBeVisible();
  });
});
